// ---------------------------------------------------------------------------
// Mock seed data for a Jira-like project management application
// ---------------------------------------------------------------------------

// ---- Helper: build dates relative to "now" so the data always feels fresh --
const now = new Date();
const daysAgo = (n) => new Date(now.getFullYear(), now.getMonth(), now.getDate() - n);
const daysFromNow = (n) => new Date(now.getFullYear(), now.getMonth(), now.getDate() + n);

// ===========================================================================
// USERS (8)
// ===========================================================================
export const mockUsers = [
  {
    id: 1,
    firstName: 'Sarah',
    lastName: 'Mitchell',
    email: 'sarah.mitchell@company.com',
    role: 'admin',
    avatar: 'https://ui-avatars.com/api/?name=Sarah+Mitchell',
  },
  {
    id: 2,
    firstName: 'James',
    lastName: 'Chen',
    email: 'james.chen@company.com',
    role: 'manager',
    avatar: 'https://ui-avatars.com/api/?name=James+Chen',
  },
  {
    id: 3,
    firstName: 'Olivia',
    lastName: 'Rodriguez',
    email: 'olivia.rodriguez@company.com',
    role: 'developer',
    avatar: 'https://ui-avatars.com/api/?name=Olivia+Rodriguez',
  },
  {
    id: 4,
    firstName: 'Daniel',
    lastName: 'Kim',
    email: 'daniel.kim@company.com',
    role: 'developer',
    avatar: 'https://ui-avatars.com/api/?name=Daniel+Kim',
  },
  {
    id: 5,
    firstName: 'Emily',
    lastName: 'Nakamura',
    email: 'emily.nakamura@company.com',
    role: 'developer',
    avatar: 'https://ui-avatars.com/api/?name=Emily+Nakamura',
  },
  {
    id: 6,
    firstName: 'Marcus',
    lastName: 'Thompson',
    email: 'marcus.thompson@company.com',
    role: 'manager',
    avatar: 'https://ui-avatars.com/api/?name=Marcus+Thompson',
  },
  {
    id: 7,
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@company.com',
    role: 'developer',
    avatar: 'https://ui-avatars.com/api/?name=Priya+Sharma',
  },
  {
    id: 8,
    firstName: 'Alex',
    lastName: 'Petrov',
    email: 'alex.petrov@company.com',
    role: 'viewer',
    avatar: 'https://ui-avatars.com/api/?name=Alex+Petrov',
  },
];

// ===========================================================================
// PROJECTS (5)
// ===========================================================================
export const mockProjects = [
  {
    id: 1,
    name: 'E-Commerce Platform Redesign',
    description:
      'Complete overhaul of the customer-facing storefront with a modern UI, improved checkout flow, and mobile-first responsive design.',
    status: 'active',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
    members: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    name: 'Internal Analytics Dashboard',
    description:
      'Real-time analytics dashboard for the operations team featuring customizable widgets, data export, and scheduled reporting.',
    status: 'active',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
    members: [1, 6, 4, 7],
  },
  {
    id: 3,
    name: 'Mobile Banking App v2',
    description:
      'Second major release of the mobile banking application with biometric login, instant transfers, and budgeting tools.',
    status: 'active',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(3),
    members: [2, 3, 5, 7, 8],
  },
  {
    id: 4,
    name: 'API Gateway Migration',
    description:
      'Migrate legacy REST endpoints to a new API gateway with rate limiting, caching, and improved authentication using OAuth 2.0.',
    status: 'on-hold',
    createdAt: daysAgo(150),
    updatedAt: daysAgo(30),
    members: [1, 4, 6],
  },
  {
    id: 5,
    name: 'Customer Support Portal',
    description:
      'Self-service support portal with a knowledge base, ticket tracking, live chat integration, and satisfaction surveys.',
    status: 'completed',
    createdAt: daysAgo(200),
    updatedAt: daysAgo(10),
    members: [2, 3, 5, 6, 8],
  },
];

// ===========================================================================
// TASKS (40) — distributed across all 5 projects
// ===========================================================================
export const mockTasks = [
  // ----- Project 1: E-Commerce Platform Redesign (tasks 1-10) -----
  {
    id: 1,
    projectId: 1,
    title: 'Implement user authentication flow',
    description:
      'Build login, registration, and password-reset screens with JWT-based auth and social OAuth providers.',
    status: 'done',
    priority: 'high',
    assigneeId: 3,
    createdAt: daysAgo(85),
    dueDate: daysAgo(60),
    tags: ['auth', 'frontend', 'security'],
  },
  {
    id: 2,
    projectId: 1,
    title: 'Design product listing page',
    description:
      'Create a responsive product grid with filtering, sorting, and infinite scroll.',
    status: 'done',
    priority: 'high',
    assigneeId: 4,
    createdAt: daysAgo(80),
    dueDate: daysAgo(55),
    tags: ['ui', 'frontend'],
  },
  {
    id: 3,
    projectId: 1,
    title: 'Build shopping cart module',
    description:
      'Persistent cart with quantity adjustment, coupon application, and real-time price calculation.',
    status: 'in-progress',
    priority: 'critical',
    assigneeId: 3,
    createdAt: daysAgo(60),
    dueDate: daysFromNow(5),
    tags: ['cart', 'frontend', 'state-management'],
  },
  {
    id: 4,
    projectId: 1,
    title: 'Integrate Stripe payment gateway',
    description:
      'Set up Stripe Elements for card payments, Apple Pay, and Google Pay with PCI-compliant tokenization.',
    status: 'todo',
    priority: 'critical',
    assigneeId: 5,
    createdAt: daysAgo(45),
    dueDate: daysFromNow(14),
    tags: ['payments', 'integration', 'security'],
  },
  {
    id: 5,
    projectId: 1,
    title: 'Create order confirmation emails',
    description:
      'Transactional email templates for order confirmation, shipping updates, and delivery notifications.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 4,
    createdAt: daysAgo(30),
    dueDate: daysFromNow(20),
    tags: ['email', 'backend'],
  },
  {
    id: 6,
    projectId: 1,
    title: 'Implement product search with Algolia',
    description:
      'Full-text product search with typo tolerance, faceted filtering, and search analytics.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 5,
    createdAt: daysAgo(40),
    dueDate: daysFromNow(7),
    tags: ['search', 'integration', 'frontend'],
  },
  {
    id: 7,
    projectId: 1,
    title: 'Set up CI/CD pipeline for staging',
    description:
      'Configure GitHub Actions to run tests, linting, and deploy to the staging environment on every merge to develop.',
    status: 'review',
    priority: 'medium',
    assigneeId: 3,
    createdAt: daysAgo(20),
    dueDate: daysFromNow(3),
    tags: ['devops', 'ci-cd'],
  },
  {
    id: 8,
    projectId: 1,
    title: 'Write E2E tests for checkout flow',
    description:
      'Cypress end-to-end tests covering cart-to-payment-to-confirmation happy path and edge cases.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 4,
    createdAt: daysAgo(15),
    dueDate: daysFromNow(18),
    tags: ['testing', 'qa'],
  },
  {
    id: 9,
    projectId: 1,
    title: 'Optimize image loading with lazy load',
    description:
      'Implement intersection-observer-based lazy loading and serve WebP/AVIF formats via a CDN.',
    status: 'todo',
    priority: 'low',
    assigneeId: 5,
    createdAt: daysAgo(10),
    dueDate: daysFromNow(25),
    tags: ['performance', 'frontend'],
  },
  {
    id: 10,
    projectId: 1,
    title: 'Add accessibility audit fixes',
    description:
      'Resolve WCAG 2.1 AA violations identified by axe-core: focus management, ARIA labels, color contrast.',
    status: 'todo',
    priority: 'high',
    assigneeId: 3,
    createdAt: daysAgo(5),
    dueDate: daysFromNow(12),
    tags: ['accessibility', 'frontend'],
  },

  // ----- Project 2: Internal Analytics Dashboard (tasks 11-18) -----
  {
    id: 11,
    projectId: 2,
    title: 'Design dashboard wireframes',
    description:
      'Low-fidelity wireframes for the main dashboard, drill-down views, and settings panel.',
    status: 'done',
    priority: 'high',
    assigneeId: 7,
    createdAt: daysAgo(55),
    dueDate: daysAgo(40),
    tags: ['design', 'ux'],
  },
  {
    id: 12,
    projectId: 2,
    title: 'Set up data ingestion pipeline',
    description:
      'Stream events from Kafka into ClickHouse with schema validation and dead-letter queue handling.',
    status: 'in-progress',
    priority: 'critical',
    assigneeId: 4,
    createdAt: daysAgo(50),
    dueDate: daysFromNow(4),
    tags: ['backend', 'data-engineering'],
  },
  {
    id: 13,
    projectId: 2,
    title: 'Build real-time chart components',
    description:
      'Reusable Vue chart components (line, bar, pie, heatmap) powered by D3.js with WebSocket live updates.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 7,
    createdAt: daysAgo(35),
    dueDate: daysFromNow(10),
    tags: ['frontend', 'charts', 'vue'],
  },
  {
    id: 14,
    projectId: 2,
    title: 'Implement date range picker and filters',
    description:
      'Global date range selector with presets (7d, 30d, 90d, custom) that propagates to all widgets.',
    status: 'review',
    priority: 'medium',
    assigneeId: 4,
    createdAt: daysAgo(25),
    dueDate: daysFromNow(2),
    tags: ['frontend', 'ux'],
  },
  {
    id: 15,
    projectId: 2,
    title: 'Create CSV/PDF export functionality',
    description:
      'Allow users to export any dashboard view as a CSV or a styled PDF report with company branding.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 7,
    createdAt: daysAgo(18),
    dueDate: daysFromNow(15),
    tags: ['backend', 'export'],
  },
  {
    id: 16,
    projectId: 2,
    title: 'Add role-based access control to dashboards',
    description:
      'Restrict dashboard visibility and editing based on user roles and team membership.',
    status: 'todo',
    priority: 'high',
    assigneeId: 4,
    createdAt: daysAgo(12),
    dueDate: daysFromNow(20),
    tags: ['security', 'backend'],
  },
  {
    id: 17,
    projectId: 2,
    title: 'Set up scheduled email reports',
    description:
      'CRON-driven service that generates and emails weekly/monthly PDF summaries to subscribers.',
    status: 'todo',
    priority: 'low',
    assigneeId: 7,
    createdAt: daysAgo(8),
    dueDate: daysFromNow(28),
    tags: ['email', 'backend', 'cron'],
  },
  {
    id: 18,
    projectId: 2,
    title: 'Performance benchmark and caching layer',
    description:
      'Profile slow queries, add Redis caching for frequently accessed aggregations, and set up monitoring alerts.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 4,
    createdAt: daysAgo(5),
    dueDate: daysFromNow(22),
    tags: ['performance', 'backend', 'redis'],
  },

  // ----- Project 3: Mobile Banking App v2 (tasks 19-28) -----
  {
    id: 19,
    projectId: 3,
    title: 'Implement biometric login',
    description:
      'Face ID / Touch ID / fingerprint authentication with secure enclave key storage and fallback PIN.',
    status: 'done',
    priority: 'critical',
    assigneeId: 5,
    createdAt: daysAgo(110),
    dueDate: daysAgo(80),
    tags: ['auth', 'mobile', 'security'],
  },
  {
    id: 20,
    projectId: 3,
    title: 'Build instant transfer screen',
    description:
      'P2P instant money transfers with payee lookup, amount validation, and confirmation step.',
    status: 'done',
    priority: 'high',
    assigneeId: 7,
    createdAt: daysAgo(100),
    dueDate: daysAgo(70),
    tags: ['mobile', 'payments'],
  },
  {
    id: 21,
    projectId: 3,
    title: 'Create budgeting tools UI',
    description:
      'Monthly budget planner with category breakdowns, spending graphs, and alerts for overspending.',
    status: 'in-progress',
    priority: 'high',
    assigneeId: 3,
    createdAt: daysAgo(60),
    dueDate: daysFromNow(8),
    tags: ['mobile', 'frontend', 'finance'],
  },
  {
    id: 22,
    projectId: 3,
    title: 'Integrate push notifications service',
    description:
      'Firebase Cloud Messaging integration for transaction alerts, security warnings, and promotional messages.',
    status: 'review',
    priority: 'medium',
    assigneeId: 5,
    createdAt: daysAgo(40),
    dueDate: daysFromNow(1),
    tags: ['mobile', 'notifications', 'integration'],
  },
  {
    id: 23,
    projectId: 3,
    title: 'Add transaction history search and filters',
    description:
      'Search bar with auto-complete plus filters by date, amount range, category, and merchant.',
    status: 'in-progress',
    priority: 'medium',
    assigneeId: 7,
    createdAt: daysAgo(35),
    dueDate: daysFromNow(6),
    tags: ['mobile', 'frontend', 'search'],
  },
  {
    id: 24,
    projectId: 3,
    title: 'Implement card freeze / unfreeze',
    description:
      'Real-time card control allowing users to temporarily freeze their debit/credit cards from the app.',
    status: 'todo',
    priority: 'high',
    assigneeId: 3,
    createdAt: daysAgo(25),
    dueDate: daysFromNow(14),
    tags: ['mobile', 'security', 'backend'],
  },
  {
    id: 25,
    projectId: 3,
    title: 'Write unit tests for transfer module',
    description:
      'Jest tests covering validation logic, error handling, and edge cases for the instant transfer feature.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 5,
    createdAt: daysAgo(20),
    dueDate: daysFromNow(16),
    tags: ['testing', 'mobile'],
  },
  {
    id: 26,
    projectId: 3,
    title: 'Dark mode theme support',
    description:
      'System-preference-aware dark mode with manual toggle and consistent theming across all screens.',
    status: 'todo',
    priority: 'low',
    assigneeId: 7,
    createdAt: daysAgo(14),
    dueDate: daysFromNow(21),
    tags: ['mobile', 'ui', 'theme'],
  },
  {
    id: 27,
    projectId: 3,
    title: 'Localization for Spanish and French',
    description:
      'i18n setup with translated strings, locale-aware date/currency formatting, and RTL preparation.',
    status: 'todo',
    priority: 'low',
    assigneeId: 3,
    createdAt: daysAgo(7),
    dueDate: daysFromNow(30),
    tags: ['i18n', 'mobile'],
  },
  {
    id: 28,
    projectId: 3,
    title: 'Security penetration testing coordination',
    description:
      'Coordinate with the external pen-testing firm, provide test accounts, and triage findings.',
    status: 'todo',
    priority: 'critical',
    assigneeId: 2,
    createdAt: daysAgo(3),
    dueDate: daysFromNow(10),
    tags: ['security', 'compliance'],
  },

  // ----- Project 4: API Gateway Migration (tasks 29-34) -----
  {
    id: 29,
    projectId: 4,
    title: 'Audit existing REST endpoints',
    description:
      'Catalogue all current endpoints, their consumers, request volumes, and deprecation candidates.',
    status: 'done',
    priority: 'high',
    assigneeId: 4,
    createdAt: daysAgo(140),
    dueDate: daysAgo(120),
    tags: ['backend', 'documentation'],
  },
  {
    id: 30,
    projectId: 4,
    title: 'Set up Kong API Gateway',
    description:
      'Deploy Kong in a Docker cluster with PostgreSQL backing, configure plugins for rate-limiting and logging.',
    status: 'done',
    priority: 'critical',
    assigneeId: 6,
    createdAt: daysAgo(130),
    dueDate: daysAgo(100),
    tags: ['devops', 'infrastructure'],
  },
  {
    id: 31,
    projectId: 4,
    title: 'Implement OAuth 2.0 authentication layer',
    description:
      'Replace API-key auth with OAuth 2.0 authorization code + PKCE flow; issue JWTs with scoped claims.',
    status: 'in-progress',
    priority: 'critical',
    assigneeId: 4,
    createdAt: daysAgo(90),
    dueDate: daysFromNow(15),
    tags: ['auth', 'security', 'backend'],
  },
  {
    id: 32,
    projectId: 4,
    title: 'Migrate user service endpoints',
    description:
      'Route /api/v1/users/* through the new gateway, update consumer SDKs, and run regression tests.',
    status: 'todo',
    priority: 'high',
    assigneeId: 6,
    createdAt: daysAgo(60),
    dueDate: daysFromNow(25),
    tags: ['backend', 'migration'],
  },
  {
    id: 33,
    projectId: 4,
    title: 'Migrate payment service endpoints',
    description:
      'Route /api/v1/payments/* with additional PCI DSS compliance headers and payload encryption.',
    status: 'todo',
    priority: 'critical',
    assigneeId: 4,
    createdAt: daysAgo(55),
    dueDate: daysFromNow(30),
    tags: ['backend', 'migration', 'security'],
  },
  {
    id: 34,
    projectId: 4,
    title: 'Create gateway monitoring dashboard',
    description:
      'Grafana dashboard showing request rates, latency percentiles, error codes, and upstream health.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 6,
    createdAt: daysAgo(40),
    dueDate: daysFromNow(35),
    tags: ['devops', 'monitoring'],
  },

  // ----- Project 5: Customer Support Portal (tasks 35-40) -----
  {
    id: 35,
    projectId: 5,
    title: 'Build knowledge base article editor',
    description:
      'Rich-text WYSIWYG editor with image uploads, code blocks, and version history for support articles.',
    status: 'done',
    priority: 'high',
    assigneeId: 3,
    createdAt: daysAgo(180),
    dueDate: daysAgo(140),
    tags: ['frontend', 'editor'],
  },
  {
    id: 36,
    projectId: 5,
    title: 'Implement ticket tracking system',
    description:
      'Full ticket lifecycle: creation, assignment, status transitions, SLA timers, and resolution tracking.',
    status: 'done',
    priority: 'critical',
    assigneeId: 5,
    createdAt: daysAgo(170),
    dueDate: daysAgo(130),
    tags: ['backend', 'frontend'],
  },
  {
    id: 37,
    projectId: 5,
    title: 'Integrate live chat with WebSocket',
    description:
      'Real-time chat widget using Socket.io, typing indicators, file sharing, and agent transfer capability.',
    status: 'done',
    priority: 'high',
    assigneeId: 6,
    createdAt: daysAgo(150),
    dueDate: daysAgo(110),
    tags: ['frontend', 'websocket', 'integration'],
  },
  {
    id: 38,
    projectId: 5,
    title: 'Create customer satisfaction surveys',
    description:
      'Post-resolution CSAT survey with star rating, free-text feedback, and automated follow-up for low scores.',
    status: 'done',
    priority: 'medium',
    assigneeId: 3,
    createdAt: daysAgo(120),
    dueDate: daysAgo(80),
    tags: ['frontend', 'ux'],
  },
  {
    id: 39,
    projectId: 5,
    title: 'Add multi-language support for portal',
    description:
      'i18n with Vue I18n for English, Spanish, French, and German; language switcher in the header.',
    status: 'done',
    priority: 'medium',
    assigneeId: 5,
    createdAt: daysAgo(100),
    dueDate: daysAgo(60),
    tags: ['i18n', 'frontend'],
  },
  {
    id: 40,
    projectId: 5,
    title: 'Final QA and launch checklist',
    description:
      'Cross-browser testing, load testing, security review, DNS switch, and go-live monitoring plan.',
    status: 'done',
    priority: 'critical',
    assigneeId: 6,
    createdAt: daysAgo(50),
    dueDate: daysAgo(15),
    tags: ['qa', 'launch'],
  },
];

// ===========================================================================
// COMMENTS (20)
// ===========================================================================
export const mockComments = [
  {
    id: 1,
    taskId: 3,
    userId: 2,
    text: 'The cart state should persist across sessions. Are we using localStorage or a server-side session?',
    createdAt: daysAgo(14),
  },
  {
    id: 2,
    taskId: 3,
    userId: 3,
    text: 'Going with Pinia persisted state plugin backed by localStorage. It syncs automatically.',
    createdAt: daysAgo(13),
  },
  {
    id: 3,
    taskId: 4,
    userId: 1,
    text: 'Make sure we support 3D Secure for European cards. Stripe has built-in support for SCA.',
    createdAt: daysAgo(10),
  },
  {
    id: 4,
    taskId: 6,
    userId: 5,
    text: 'Algolia free tier only allows 10k records. Should we request an upgrade or self-host Meilisearch?',
    createdAt: daysAgo(9),
  },
  {
    id: 5,
    taskId: 6,
    userId: 2,
    text: 'Budget approved for Algolia Pro. Go ahead with the integration as planned.',
    createdAt: daysAgo(8),
  },
  {
    id: 6,
    taskId: 7,
    userId: 3,
    text: 'CI pipeline is green on all branches. Ready for final review before merging to main.',
    createdAt: daysAgo(4),
  },
  {
    id: 7,
    taskId: 12,
    userId: 6,
    text: 'The Kafka consumer is lagging during peak hours. We might need to increase partition count.',
    createdAt: daysAgo(7),
  },
  {
    id: 8,
    taskId: 12,
    userId: 4,
    text: 'Increased partitions from 6 to 12 and added a second consumer group. Lag is back to normal.',
    createdAt: daysAgo(5),
  },
  {
    id: 9,
    taskId: 13,
    userId: 7,
    text: 'D3.js transitions are causing jank on lower-end devices. Looking into canvas-based rendering instead.',
    createdAt: daysAgo(6),
  },
  {
    id: 10,
    taskId: 14,
    userId: 4,
    text: 'Date picker component is ready. Please review the UX for the custom range selection flow.',
    createdAt: daysAgo(3),
  },
  {
    id: 11,
    taskId: 21,
    userId: 3,
    text: 'The budget pie chart needs a color palette that is distinguishable for color-blind users.',
    createdAt: daysAgo(8),
  },
  {
    id: 12,
    taskId: 22,
    userId: 5,
    text: 'Push notification permissions are tricky on iOS. We need to request at the right moment in the UX.',
    createdAt: daysAgo(5),
  },
  {
    id: 13,
    taskId: 22,
    userId: 2,
    text: 'Agreed. Lets prompt after the first successful transfer, not on app launch.',
    createdAt: daysAgo(4),
  },
  {
    id: 14,
    taskId: 28,
    userId: 2,
    text: 'The pen-testing firm confirmed availability starting next week. I will create test accounts by Friday.',
    createdAt: daysAgo(2),
  },
  {
    id: 15,
    taskId: 31,
    userId: 4,
    text: 'PKCE flow is implemented. Need to update the developer portal docs with the new auth sequence.',
    createdAt: daysAgo(6),
  },
  {
    id: 16,
    taskId: 31,
    userId: 1,
    text: 'Great progress. Make sure refresh token rotation is enabled to prevent token replay attacks.',
    createdAt: daysAgo(4),
  },
  {
    id: 17,
    taskId: 35,
    userId: 3,
    text: 'The editor supports Markdown shortcuts now. Bold, italic, headings, and code blocks all work.',
    createdAt: daysAgo(45),
  },
  {
    id: 18,
    taskId: 36,
    userId: 6,
    text: 'SLA timer pauses correctly when a ticket is in "waiting on customer" status. QA verified.',
    createdAt: daysAgo(40),
  },
  {
    id: 19,
    taskId: 37,
    userId: 5,
    text: 'WebSocket reconnection logic handles network drops gracefully. Tested with throttled connections.',
    createdAt: daysAgo(35),
  },
  {
    id: 20,
    taskId: 40,
    userId: 6,
    text: 'All QA checks passed. DNS propagation is complete. The portal is live and monitoring looks clean.',
    createdAt: daysAgo(14),
  },
];

// ===========================================================================
// NOTIFICATIONS (15)
// ===========================================================================
export const mockNotifications = [
  {
    id: 1,
    type: 'task-assigned',
    message: 'You have been assigned to "Build shopping cart module".',
    userId: 3,
    read: true,
    createdAt: daysAgo(60),
  },
  {
    id: 2,
    type: 'comment-added',
    message: 'James Chen commented on "Build shopping cart module".',
    userId: 3,
    read: true,
    createdAt: daysAgo(14),
  },
  {
    id: 3,
    type: 'deadline-approaching',
    message: 'Deadline for "Integrate Stripe payment gateway" is in 14 days.',
    userId: 5,
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: 4,
    type: 'task-assigned',
    message: 'You have been assigned to "Set up data ingestion pipeline".',
    userId: 4,
    read: true,
    createdAt: daysAgo(50),
  },
  {
    id: 5,
    type: 'project-updated',
    message: 'Project "API Gateway Migration" has been put on hold.',
    userId: 4,
    read: true,
    createdAt: daysAgo(30),
  },
  {
    id: 6,
    type: 'comment-added',
    message: 'Marcus Thompson commented on "Set up data ingestion pipeline".',
    userId: 4,
    read: false,
    createdAt: daysAgo(7),
  },
  {
    id: 7,
    type: 'task-assigned',
    message: 'You have been assigned to "Create budgeting tools UI".',
    userId: 3,
    read: true,
    createdAt: daysAgo(60),
  },
  {
    id: 8,
    type: 'deadline-approaching',
    message: 'Deadline for "Build real-time chart components" is in 10 days.',
    userId: 7,
    read: false,
    createdAt: daysAgo(1),
  },
  {
    id: 9,
    type: 'comment-added',
    message: 'Sarah Mitchell commented on "Implement OAuth 2.0 authentication layer".',
    userId: 4,
    read: false,
    createdAt: daysAgo(4),
  },
  {
    id: 10,
    type: 'project-updated',
    message: 'Project "Customer Support Portal" has been marked as completed.',
    userId: 6,
    read: true,
    createdAt: daysAgo(10),
  },
  {
    id: 11,
    type: 'task-assigned',
    message: 'You have been assigned to "Security penetration testing coordination".',
    userId: 2,
    read: false,
    createdAt: daysAgo(3),
  },
  {
    id: 12,
    type: 'deadline-approaching',
    message: 'Deadline for "Implement date range picker and filters" is in 2 days.',
    userId: 4,
    read: false,
    createdAt: daysAgo(0),
  },
  {
    id: 13,
    type: 'comment-added',
    message: 'Olivia Rodriguez commented on "Create budgeting tools UI".',
    userId: 2,
    read: false,
    createdAt: daysAgo(8),
  },
  {
    id: 14,
    type: 'project-updated',
    message: 'New members added to "Internal Analytics Dashboard".',
    userId: 7,
    read: true,
    createdAt: daysAgo(15),
  },
  {
    id: 15,
    type: 'deadline-approaching',
    message: 'Deadline for "Set up CI/CD pipeline for staging" is in 3 days.',
    userId: 3,
    read: false,
    createdAt: daysAgo(0),
  },
];

// ===========================================================================
// ACTIVITY LOG (20)
// ===========================================================================
export const mockActivities = [
  {
    id: 1,
    type: 'task-created',
    message: 'Sarah Mitchell created task "Add accessibility audit fixes".',
    userId: 1,
    entityType: 'task',
    entityId: 10,
    createdAt: daysAgo(5),
  },
  {
    id: 2,
    type: 'task-status-changed',
    message: 'Olivia Rodriguez moved "Implement user authentication flow" to Done.',
    userId: 3,
    entityType: 'task',
    entityId: 1,
    createdAt: daysAgo(60),
  },
  {
    id: 3,
    type: 'comment-added',
    message: 'James Chen commented on "Build shopping cart module".',
    userId: 2,
    entityType: 'comment',
    entityId: 1,
    createdAt: daysAgo(14),
  },
  {
    id: 4,
    type: 'project-created',
    message: 'Sarah Mitchell created project "E-Commerce Platform Redesign".',
    userId: 1,
    entityType: 'project',
    entityId: 1,
    createdAt: daysAgo(90),
  },
  {
    id: 5,
    type: 'task-assigned',
    message: 'Emily Nakamura was assigned to "Integrate Stripe payment gateway".',
    userId: 2,
    entityType: 'task',
    entityId: 4,
    createdAt: daysAgo(45),
  },
  {
    id: 6,
    type: 'task-status-changed',
    message: 'Daniel Kim moved "Implement date range picker and filters" to Review.',
    userId: 4,
    entityType: 'task',
    entityId: 14,
    createdAt: daysAgo(3),
  },
  {
    id: 7,
    type: 'project-status-changed',
    message: 'Sarah Mitchell changed "API Gateway Migration" status to On Hold.',
    userId: 1,
    entityType: 'project',
    entityId: 4,
    createdAt: daysAgo(30),
  },
  {
    id: 8,
    type: 'task-status-changed',
    message: 'Emily Nakamura moved "Implement biometric login" to Done.',
    userId: 5,
    entityType: 'task',
    entityId: 19,
    createdAt: daysAgo(80),
  },
  {
    id: 9,
    type: 'member-added',
    message: 'Priya Sharma was added to project "Internal Analytics Dashboard".',
    userId: 1,
    entityType: 'project',
    entityId: 2,
    createdAt: daysAgo(55),
  },
  {
    id: 10,
    type: 'comment-added',
    message: 'Emily Nakamura commented on "Integrate push notifications service".',
    userId: 5,
    entityType: 'comment',
    entityId: 12,
    createdAt: daysAgo(5),
  },
  {
    id: 11,
    type: 'task-created',
    message: 'James Chen created task "Security penetration testing coordination".',
    userId: 2,
    entityType: 'task',
    entityId: 28,
    createdAt: daysAgo(3),
  },
  {
    id: 12,
    type: 'project-status-changed',
    message: 'Marcus Thompson changed "Customer Support Portal" status to Completed.',
    userId: 6,
    entityType: 'project',
    entityId: 5,
    createdAt: daysAgo(10),
  },
  {
    id: 13,
    type: 'task-status-changed',
    message: 'Olivia Rodriguez moved "Set up CI/CD pipeline for staging" to Review.',
    userId: 3,
    entityType: 'task',
    entityId: 7,
    createdAt: daysAgo(4),
  },
  {
    id: 14,
    type: 'comment-added',
    message: 'Daniel Kim commented on "Set up data ingestion pipeline".',
    userId: 4,
    entityType: 'comment',
    entityId: 8,
    createdAt: daysAgo(5),
  },
  {
    id: 15,
    type: 'task-assigned',
    message: 'Priya Sharma was assigned to "Build real-time chart components".',
    userId: 6,
    entityType: 'task',
    entityId: 13,
    createdAt: daysAgo(35),
  },
  {
    id: 16,
    type: 'task-status-changed',
    message: 'Marcus Thompson moved "Final QA and launch checklist" to Done.',
    userId: 6,
    entityType: 'task',
    entityId: 40,
    createdAt: daysAgo(14),
  },
  {
    id: 17,
    type: 'member-added',
    message: 'Alex Petrov was added to project "Customer Support Portal".',
    userId: 2,
    entityType: 'project',
    entityId: 5,
    createdAt: daysAgo(190),
  },
  {
    id: 18,
    type: 'task-created',
    message: 'Marcus Thompson created task "Create gateway monitoring dashboard".',
    userId: 6,
    entityType: 'task',
    entityId: 34,
    createdAt: daysAgo(40),
  },
  {
    id: 19,
    type: 'comment-added',
    message: 'Priya Sharma commented on "Build real-time chart components".',
    userId: 7,
    entityType: 'comment',
    entityId: 9,
    createdAt: daysAgo(6),
  },
  {
    id: 20,
    type: 'task-status-changed',
    message: 'Priya Sharma moved "Add transaction history search and filters" to In Progress.',
    userId: 7,
    entityType: 'task',
    entityId: 23,
    createdAt: daysAgo(2),
  },
];
